export const hi = {
  welcome: "स्वागत है",
  print: "प्रिंट",
  noDataAvailable: "कोई ज्योतिष डेटा उपलब्ध नहीं",
  completeProfile:
    "कृपया अपनी ब्रह्मांडीय अंतर्दृष्टि उत्पन्न करने के लिए अपनी प्रोफ़ाइल पूरी करें।",
  completeProfileButton: "प्रोफ़ाइल पूरी करें",
  birthDetails: "जन्म विवरण",
  dateOfBirth: "जन्म तिथि:",
  birthTime: "जन्म समय:",
  birthPlace: "जन्म स्थान:",
  nakshatra: "नक्षत्र:",
  nakshatraLord: "नक्षत्र स्वामी:",
  gana: "गण:",
  yoni: "योनि:",
  astrologyCharts: "ज्योतिष चार्ट",
  charts: "चार्ट",
  chartsDescription:
    "कुंडली वैदिक ज्योतिष में जन्म चार्ट के लिए प्रयुक्त शब्द है। कुंडली के बारह घर जन्म के समय विभिन्न राशियों में लग्न और ग्रह स्थिति दिखाते हैं। सटीक कुंडली निर्माण के लिए जन्म स्थान, तारीख और समय महत्वपूर्ण हैं।",
  planetaryPositions: "ग्रह स्थितियां",
  planetaryDescription:
    "ग्रह स्थितियां व्यक्ति के जीवन के विभिन्न पहलुओं को निर्धारित करने में महत्वपूर्ण भूमिका निभाती हैं। ग्रहों और अन्य खगोलीय पिंडों का संरेखण एक महत्वपूर्ण कारक है जो व्यक्तिगत कुंडली भी तय करता है।",
  chatWithAI: "AI ज्योतिषी से चैट करें",
  freeChatsLeft: "आज बचे मुफ्त चैट:",
  askQuestion: "अपनी ब्रह्मांडीय यात्रा के बारे में मुझसे कुछ भी पूछें!",
  typeQuestion: "अपना प्रश्न टाइप करें...",
  send: "भेजें",
  sending: "भेज रहे हैं...",
  house: "भाव",
  chartLoading: "चार्ट लोड हो रहा है...",
  lagnaChart: "लग्न चार्ट",
  chandraChart: "चंद्र चार्ट",
  navamsaChart: "नवांश चार्ट",
  horaChart: "होरा (धन - D2)",
  drekkanaChart: "द्रेक्कन (भाई-बहन - D3)",
  chaturtamshaChart: "चतुर्तमांश (भाग्य - D4)",
  saptamshaChart: "सप्तमांश (बच्चे - D7)",
  navamshaChart: "नवमांश (जीवनसाथी - D9)",
  dashamshaChart: "दशमांश (पेशे - D10)",
  dwadashamshaChart: "द्वादशांश (माता-पिता - D12)",
  shodasamshaChart: "शोडशांश (वाहन - D16)",
  vimshamshaChart: "विम्शमांश (धार्मिक झुकाव - D20)",
  chaturvimshamshaChart: "चतुर्विम्शमांश (शिक्षा - D24)",
  saptavimshaChart: "सप्तविम्शमांश (शक्ति - D27)",
  trimsamshaChart: "त्रिम्समांश (दुर्भाग्य - D30)",
  khavedamshaChart: "खवेदमांश (शुभ परिणाम - D40)",
  shashtiamshaChart: "शष्ठियामांश (सामान्य कल्याण - D60)",
};
