import { Moon } from "lucide-react";

export const ma = {
  welcome: "स्वागत आहे",
  print: "प्रिंट",
  noDataAvailable: "कोणताही ज्योतिष डेटा उपलब्ध नाही",
  completeProfile:
    "कृपया आपल्या ब्रह्मांडीय अंतर्दृष्टि निर्माण करण्यासाठी आपली प्रोफाइल पूर्ण करा.",
  completeProfileButton: "प्रोफाइल पूर्ण करा",
  birthDetails: "जन्म तपशील",
  dateOfBirth: "जन्म तारीख:",
  birthTime: "जन्म वेळ:",
  birthPlace: "जन्म जागा:",
  nakshatra: "नक्षत्र:",
  nakshatraLord: "नक्षत्र स्वामी:",
  gana: "गण:",
  yoni: "योनि:",
  astrologyCharts: "ज्योतिष चार्ट",
  charts: "चार्ट",
  chartsDescription:
    "कुंडली वैदिक ज्योतिषामध्ये जन्म चार्टसाठी वापरलेला शब्द आहे. कुंडलीचे बाराह घर जन्माच्या वेळी विविध राशींमध्ये लग्न आणि ग्रह स्थिती दर्शवतात. अचूक कुंडली तयार करण्यासाठी जन्म स्थान, तारीख आणि वेळ महत्त्वाची असते.",
  planetaryPositions: "ग्रह स्थिती",
  planetaryDescription:
    "ग्रह स्थिती व्यक्तीच्या जीवनाच्या विविध पैलूंना निश्चित करण्यात महत्त्वपूर्ण भूमिका बजावतात. ग्रह आणि इतर खगोलीय पिंडांचे संरेखण एक महत्त्वाचा घटक आहे जो वैयक्तिक कुंडली देखील ठरवतो.",
  chatWithAI: "AI ज्योतिषीशी चॅट करा",
  freeChatsLeft: "आज बचेलेले मोफत चॅट:",
  askQuestion: "आपल्या ब्रह्मांडीय यात्रा बद्दल मुझसे काहीही विचारा!",
  typeQuestion: "आपला प्रश्न टाइप करा...",
  send: "पाठवा",
  sending: "पाठवत आहे...",
  house: "भाव",
  chartLoading: "चार्ट लोड होत आहे...",
  lagnaChart: "लग्न चार्ट",
  chandraChart: "चंद्र चार्ट",
  navamsaChart: "नवांश चार्ट",
  ashtakvargaChart: "अष्टकवर्ग चार्ट",
  horaChart: "होरा (धन - D2)",
  drekkanaChart: "द्रेक्कन (भाई-बहन - D3)",
  chaturtamshaChart: "चतुर्तमांश (भाग्य - D4)",
  saptamshaChart: "सप्तमांश (बच्चे - D7)",
  navamshaChart: "नवमांश (जीवनसाथी - D9)",
  dashamshaChart: "दशमांश (पेशे - D10)",
  dwadashamshaChart: "द्वादशांश (माता-पिता - D12)",
  shodasamshaChart: "शोडशांश (वाहन - D16)",
  vimshamshaChart: "विम्शमांश (धार्मिक झुकाव - D20)",
  chaturvimshamshaChart: "चतुर्विम्शमांश (शिक्षा - D24)",
  saptavimshaChart: "सप्तविम्शमांश (शक्ति - D27)",
  trimsamshaChart: "त्रिम्समांश (दुर्भाग्य - D30)",
  khavedamshaChart: "खवेदमांश (शुभ परिणाम - D40)",
  shashtiamshaChart: "शष्ठियामांश (सामान्य कल्याण - D60)",

  // Favorable Gemstone Section
  beneficGemstone: "फायदेशीर रत्न",
  lifeGemstone: "जीवन रत्न",
  luckyGemstone: "भाग्यवान रत्न",
  gemStones: "रत्न",
  favorableGemstone: "अनुकूल रत्न",
  ruby: "माणिक",
  emerald: "पन्ना",
  diamond: "हिरा",
  pearl: "मोती",
  coral: "प्रवाळ",
  yellowsapphire: "पुष्पराग",
  bluesapphire: "नीलमणी",
  hessonite: "गोमेद",
  cateye: "वैदूर्य",
  redcoral: "लाल मूंगा",

  // Other translations
  // noDataAvailable: "कोणता डेटा उपलब्ध नाही",
  // completeProfile: "चार्ट तयार करण्यासाठी कृपया आपले प्रोफाइल पूर्ण करा",
  goToLogin: "लॉगिनवर जा",

  MoonPrediction: "चंद्र भविष्यवाणी",
  RasiPrediction: "राशि भविष्यवाणी",
  NakshatraPrediction: "नक्षत्र भविष्यवाणी",
  panchangPrediction: "पंचांग भविष्यवाणी",
  panchangExplanation:
    "वैदिक ज्योतिषशास्त्र कुंडलीसाठी सूर्य राशींपेक्षा चंद्र राशींना जास्त महत्त्व देते. खरं तर, वैदिक ज्योतिषशास्त्र असे घोषित करते की जर चंद्र लग्नापेक्षा बलवान असेल तर लग्न किंवा उदय राशीऐवजी चंद्र राशीला जन्मकुंडलीचा केंद्र मानले पाहिजे. चंद्र राशीच्या कुंडली व्यक्तिमत्त्वाचे अनेक लपलेले रहस्य उघड करतात जे सूर्य राशींद्वारे उघड केले जाऊ शकत नाहीत.",

  explanation: "स्पष्टीकरण",
  predictionInsights: "भविष्यवाणी अंतर्दृष्टि",
  zodiacSign: "रास",
  health: "आरोग्य",
  physical: "शारीरिक",
  temp: "तापमान",

  libra: "तूळ",
  scorpio: "वृश्चिक",
  sagittarius: "धनु",
  capricorn: "मकर",
  aquarius: "कुंभ",
  pisces: "मीन",
  aries: "मेष",
  taurus: "वृषभ",
  gemini: "मिथुन",
  cancer: "कर्क",
  leo: "सिंह",
  virgo: "कन्या",
};
